const AuthActionTypes = {
  SET_USER_DATA: "SET_USER_DATA",
  IS_LOGIN_USER: "IS_LOGIN_USER",
  SIGN_UP_USER: "SIGN_UP_USER",
  SIGN_UP_USER_SUCCESS: "SIGN_UP_USER_SUCCESS",
  SIGN_UP_USER_FAILED: "SIGN_UP_USER_FAILED",
  // signin
  SET_SIGN_IN_USER_DETAILS: "SET_SIGN_IN_USER_DETAILS",
  SIGN_IN_USER_SUCCESS: "SIGN_IN_USER_SUCCESS",
  SIGN_IN_USER_FAILED: "SIGN_IN_USER_FAILED",
  //
  CLICK_START: "CLICK_START",
  CLICK_START_SUCCESS: "",
  SIGN_OUT_USER: "SIGN_OUT_USER",
  USER_SIGN_OUT_SUCCESS: "USER_SIGN_OUT_SUCCESS",
};

export default AuthActionTypes;
