const CompanyJobsActionTypes = {
  GET_ALL_COMPANY_JOBS: "GET_ALL_COMPANY_JOBS",
  GET_ALL_COMPABY_JOBS_SUCCESS: "GET_ALL_COMPABY_JOBS_SUCCESS",
  GET_ALL_COMPABY_JOBS_FAILED: "GET_ALL_COMPABY_JOBS_FAILED",
  GET_COMPANY_JOB: "GET_COMPANY_JOB",
  GET_COMPANY_JOB_SUCCESS: "GET_COMPANY_JOB_SUCCESS",
  GET_COMPANY_JOB_FAILED: "GET_COMPANY_JOB_FAILED",
  ADD_COMPANY_JOB: "ADD_COMPANY_JOB",
  ADD_COMPANY_JOB_SUCCESS: "ADD_COMPANY_JOB_SUCCESS",
  ADD_COMPANY_JOB_FAILED: "ADD_COMPANY_JOB_FAILED",
  UPDATE_COMPANY_JOB: "UPDATE_COMPANY_JOB",
  UPDATE_COMPANY_JOB_SUCCESS: "UPDATE_COMPANY_JOB_SUCCESS",
  UPDATE_COMPANY_JOB_FAILED: "UPDATE_COMPANY_JOB_FAILED",
  DELETE_COMPANY_JOB: "DELETE_COMPANY_JOB",
  DELETE_COMPANY_JOB_SUCCESS: "DELETE_COMPANY_JOB_SUCCESS",
  DELETE_COMPANY_JOB_FAILED: "DELETE_COMPANY_JOB_FAILED",
};

export default CompanyJobsActionTypes;
