const JobsActionTypes = {
  GET_ALL_JOBS_START: "GET_ALL_JOBS_START",
  GET_ALL_JOBS_SUCCESS: "GET_ALL_JOBS_SUCCESS",
  GET_ALL_JOBS_FAILED: "GET_ALL_JOBS_FAILED",
  GET_JOBS_BY_QUERY_START: "GET_JOBS_BY_QUERY_START",
  GET_JOBS_BY_QUERY_SUCCESS: "GET_JOBS_BY_QUERY_SUCCESS",
  GET_JOBS_BY_QUERY_FAILED: "GET_JOBS_BY_QUERY_FAILED",
};

export default JobsActionTypes;
