const SavedStudentJobsActionType = {
  SAVE_STUDENT_JOB_START: "SAVE_STUDENT_JOB_START",
  SAVE_STUDENT_JOB_SUCCESS: "SAVE_STUDENT_JOB_SUCCESS",
  SAVE_STUDENT_JOB_FAILED: "SAVE_STUDENT_JOB_FAILED",
  DELETE_STUDENT_JOB_START: "DELETE_STUDENT_JOB_START",
  DELETE_STUDENT_JOB_SUCCESS: "DELETE_STUDENT_JOB_SUCCESS",
  DELETE_STUDENT_JOB_FAILED: "DELETE_STUDENT_JOB_FAILED",
};

export default SavedStudentJobsActionType;
