const StudentApplicationTypes = {
  GET_STUDENT_APPLICATIONS: "GET_STUDENT_APPLICATIONS",
  GET_STUDENT_APPLICATIONS_SUCCESS: "GET_STUDENT_APPLICATIONS_SUCCESS",
  GET_STUDENT_APPLICATIONS_FAILED: "GET_STUDENT_APPLICATIONS_FAILED",
};

export default StudentApplicationTypes;
