const UserProfileActionTypes = {
  SET_USER_PROFILE_DATA: "SET_USER_PROFILE_DATA",
  UPDATE_USER_DETAILS: "UPDATE_USER_DETAILS",
  SET_UPDATE_USER_JOB_DETAILS: "SET_UPDATE_USER_DETAILS",
  SET_UPDATE_USER_JOB_DETAILS_SUCCESS: "SET_UPDATE_USER_DETAILS",
  SET_UPDATE_USER_JOB_DETAILS_FAILED: "SET_UPDATE_USER_DETAILS_FAILED",
  GET_USER_DETAILS_START: "GET_USER_DETAILS_START",
  GET_USER_DETAILS_SUCCESS: " GET_USER_DETAILS_SUCCESS",
  GET_USER_DETAILS_FAILED: "GET_USER_DETAILS_FAILED",
};

export default UserProfileActionTypes;
